### ISSUE TITLE
Heroku: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/ClassMateBot#46]
AttributeError: 'NoneType' object has no attribute 'strip'

Until this is resolved, the worker dyno will be disabled. The bot still runs on local machines and database transactions are still functional.

```
2021-11-12T22:30:52.703784+00:00 heroku[worker.1]: Starting process with command `python3 bot.py`
2021-11-12T22:30:53.507150+00:00 heroku[worker.1]: State changed from starting to up
2021-11-12T22:30:54.262532+00:00 app[worker.1]: Traceback (most recent call last):
2021-11-12T22:30:54.262548+00:00 app[worker.1]: File "/app/bot.py", line 217, in <module>
2021-11-12T22:30:54.262737+00:00 app[worker.1]: bot.run(TOKEN)
2021-11-12T22:30:54.262748+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/discord/client.py", line 723, in run
2021-11-12T22:30:54.263087+00:00 app[worker.1]: return future.result()
2021-11-12T22:30:54.263099+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/discord/client.py", line 702, in runner
2021-11-12T22:30:54.263625+00:00 app[worker.1]: await self.start(*args, **kwargs)
2021-11-12T22:30:54.263637+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/discord/client.py", line 665, in start
2021-11-12T22:30:54.263937+00:00 app[worker.1]: await self.login(*args, bot=bot)
2021-11-12T22:30:54.263949+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/discord/client.py", line 511, in login
2021-11-12T22:30:54.264186+00:00 app[worker.1]: await self.http.static_login(token.strip(), bot=bot)
2021-11-12T22:30:54.264215+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'strip'
2021-11-12T22:30:54.521397+00:00 heroku[worker.1]: Process exited with status 1
2021-11-12T22:30:54.912031+00:00 heroku[worker.1]: State changed from up to crashed

```

**Comment by snapcat** [comment]
Resolved by adding bot token to Heroku config vars. Updated the wiki to include this.
